### ISSUE TITLE
Setup fails on Ubuntu

### ISSUE THREAD

**Issue by avive** [spacemeshos/local-testnet#11]
When running `python testnet.py` we get this error:

`docker.errors.APIError: 403 Client Error: Forbidden ("Pool overlaps with other one on this address space")`

Full log:

```
(venv) parallels@parallels-Parallels-Virtual-Platform:~/dev/local-testnet$ python testnet.py
Traceback (most recent call last):
  File "/home/parallels/dev/local-testnet/venv/lib/python3.6/site-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/home/parallels/dev/local-testnet/venv/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: http+docker://localhost/v1.35/networks/create

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "testnet.py", line 209, in <module>
    create_network(NETWORK_NAME, NETWORK_SUBNET, NETWORK_GATEWAY)
  File "testnet.py", line 131, in create_network
    ipam=ipam_config
  File "/home/parallels/dev/local-testnet/venv/lib/python3.6/site-packages/docker/models/networks.py", line 154, in create
    resp = self.client.api.create_network(name, *args, **kwargs)
  File "/home/parallels/dev/local-testnet/venv/lib/python3.6/site-packages/docker/api/network.py", line 152, in create_network
    return self._result(res, json=True)
  File "/home/parallels/dev/local-testnet/venv/lib/python3.6/site-packages/docker/api/client.py", line 267, in _result
    self._raise_for_status(response)
  File "/home/parallels/dev/local-testnet/venv/lib/python3.6/site-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/parallels/dev/local-testnet/venv/lib/python3.6/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 403 Client Error: Forbidden ("Pool overlaps with other one on this address space")
Starting to shutdown nodes
Killing all dockers
[Traceback (most recent call last):
  File "testnet.py", line 245, in <module>
    tools.cleanUp(containers)
  File "/home/parallels/dev/local-testnet/tools.py", line 105, in cleanUp
    cont.kill()
AttributeError: 'NoneType' object has no attribute 'kill'
```

**Comment by avive** [comment]
docker cleanup issue. Will clarify in the readme.
