### ISSUE TITLE
Can't run anything

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/local-testnet#19]
I'm having a lot of trouble running local-testnet. It builds the docker containers correctly and appears to launch three of them. Two of them, `go-spacemesh:develop` and `poet:develop` appear to exit immediately and furthermore I cannot view their logs:

```
> docker logs -f f6c5304f66b2
Error response from daemon: configured logging driver does not support reading
> docker logs -f 9294b6bd44e5
Error response from daemon: configured logging driver does not support reading
```

The third container, `fluent/fluentd`, contains errors in the log:

```
> docker logs 81b1edffa607
2020-01-15 22:45:32 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/test.conf"
2020-01-15 22:45:32 +0000 [info]: using configuration file: <ROOT>
  <source>
    @type forward
  </source>
  <filter docker.**>
    @type parser
    key_name "log"
    format json
    reserve_data true
    <parse>
      @type json
    </parse>
  </filter>
  <match docker.*>
    @type copy
    <store>
      @type "stdout"
      include_tag_key true
      <format>
        @type "json"
      </format>
      <inject>
        tag_key tag
      </inject>
    </store>
    <store>
      @type "file"
      path "/tmp/logs/nodes.log"
      <buffer>
        timekey_use_utc true
        timekey 1h
        append true
        timekey_wait 1s
        path "/tmp/logs/nodes.log"
      </buffer>
    </store>
  </match>
</ROOT>
2020-01-15 22:45:32 +0000 [info]: starting fluentd-1.3.2 pid=6 ruby="2.5.2"
2020-01-15 22:45:32 +0000 [info]: spawn command to main:  cmdline=["/usr/bin/ruby", "-Eascii-8bit:ascii-8bit", "/usr/bin/fluentd", "-c", "/fluentd/etc/test.conf", "-p", "/fluentd/plugins", "--under-supervisor"]
2020-01-15 22:45:33 +0000 [info]: gem 'fluentd' version '1.3.2'
2020-01-15 22:45:33 +0000 [info]: adding filter pattern="docker.**" type="parser"
2020-01-15 22:45:33 +0000 [info]: adding match pattern="docker.*" type="copy"
2020-01-15 22:45:33 +0000 [info]: adding source type="forward"
2020-01-15 22:45:33 +0000 [warn]: parameter 'append' in <buffer>
  timekey_use_utc true
  timekey 1h
  append true
  timekey_wait 1s
  path "/tmp/logs/nodes.log"
</buffer> is not used.
2020-01-15 22:45:33 +0000 [info]: #0 starting fluentd worker pid=16 ppid=6 worker=0
2020-01-15 22:45:33 +0000 [info]: #0 listening port port=24224 bind="0.0.0.0"
2020-01-15 22:45:33 +0000 [info]: #0 fluentd worker is now running worker=0
2020-01-15 22:45:33 +0000 [warn]: #0 dump an error event: error_class=Fluent::Plugin::Parser::ParserError error="pattern not match with data 'unknown flag `nodeaddr''" location=nil tag="docker.poet_9294b6bd44e5" time=1579128333 record={"container_id"=>"9294b6bd44e52dfc563939e10cc578a1be5ab555cfc70d9ccc08a3a72c0e4ed3", "container_name"=>"/wonderful_shirley", "source"=>"stderr", "log"=>"unknown flag `nodeaddr'"}
{"container_id":"9294b6bd44e52dfc563939e10cc578a1be5ab555cfc70d9ccc08a3a72c0e4ed3","container_name":"/wonderful_shirley","source":"stderr","log":"unknown flag `nodeaddr'","tag":"docker.poet_9294b6bd44e5"}
2020-01-15 22:45:33 +0000 [warn]: #0 dump an error event: error_class=Fluent::Plugin::Parser::ParserError error="pattern not match with data 'unknown flag `nodeaddr''" location=nil tag="docker.poet_9294b6bd44e5" time=1579128333 record={"container_id"=>"9294b6bd44e52dfc563939e10cc578a1be5ab555cfc70d9ccc08a3a72c0e4ed3", "container_name"=>"/wonderful_shirley", "source"=>"stderr", "log"=>"unknown flag `nodeaddr'"}
{"container_id":"9294b6bd44e52dfc563939e10cc578a1be5ab555cfc70d9ccc08a3a72c0e4ed3","container_name":"/wonderful_shirley","source":"stderr","log":"unknown flag `nodeaddr'","tag":"docker.poet_9294b6bd44e5"}
{"container_id":"b6c4faf1c321c93330fc1bc6d667dbae35b1723a99e0ccdb722b9ee95a406900","container_name":"/bootstrap","source":"stdout","log":"{\"L\":\"ERROR\",\"T\":\"2020-01-15T22:45:34.735Z\",\"N\":\"00000.defaultLogger\",\"M\":\"harness: an error has occurred while generating a new harness: \",\"error\":\"could not find executable path in arguments\"}","L":"ERROR","T":"2020-01-15T22:45:34.735Z","N":"00000.defaultLogger","M":"harness: an error has occurred while generating a new harness: ","error":"could not find executable path in arguments","tag":"docker.b6c4faf1c321"}
{"container_name":"/bootstrap","source":"stdout","log":"{\"L\":\"INFO\",\"T\":\"2020-01-15T22:45:34.735Z\",\"N\":\"00000.defaultLogger\",\"M\":\"integration: harness is listening on a blocking dummy channel\"}","container_id":"b6c4faf1c321c93330fc1bc6d667dbae35b1723a99e0ccdb722b9ee95a406900","L":"INFO","T":"2020-01-15T22:45:34.735Z","N":"00000.defaultLogger","M":"integration: harness is listening on a blocking dummy channel","tag":"docker.b6c4faf1c321"}
2020-01-15 22:45:34 +0000 [warn]: #0 dump an error event: error_class=Fluent::Plugin::Parser::ParserError error="pattern not match with data 'panic: runtime error: invalid memory address or nil pointer dereference'" location=nil tag="docker.b6c4faf1c321" time=1579128334 record={"log"=>"panic: runtime error: invalid memory address or nil pointer dereference", "container_id"=>"b6c4faf1c321c93330fc1bc6d667dbae35b1723a99e0ccdb722b9ee95a406900", "container_name"=>"/bootstrap", "source"=>"stderr"}
{"log":"panic: runtime error: invalid memory address or nil pointer dereference","container_id":"b6c4faf1c321c93330fc1bc6d667dbae35b1723a99e0ccdb722b9ee95a406900","container_name":"/bootstrap","source":"stderr","tag":"docker.b6c4faf1c321"}
2020-01-15 22:45:34 +0000 [warn]: #0 dump an error event: error_class=Fluent::Plugin::Parser::ParserError error="pattern not match with data '[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8306fa]'" location=nil tag="docker.b6c4faf1c321" time=1579128334 record={"container_name"=>"/bootstrap", "source"=>"stderr", "log"=>"[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8306fa]", "container_id"=>"b6c4faf1c321c93330fc1bc6d667dbae35b1723a99e0ccdb722b9ee95a406900"}
{"container_name":"/bootstrap","source":"stderr","log":"[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8306fa]","container_id":"b6c4faf1c321c93330fc1bc6d667dbae35b1723a99e0ccdb722b9ee95a406900","tag":"docker.b6c4faf1c321"}
2020-01-15 22:45:34 +0000 [warn]: #0 dump an error event: error_class=Fluent::Plugin::Parser::ParserError error="pattern not match with data ''" location=nil tag="docker.b6c4faf1c321" time=1579128334 record={"container_id"=>"b6c4faf1c321c93330fc1bc6d667dbae35b1723a99e0ccdb722b9ee95a406900", "container_name"=>"/bootstrap", "source"=>"stderr", "log"=>""}
{"container_id":"b6c4faf1c321c93330fc1bc6d667dbae35b1723a99e0ccdb722b9ee95a406900","container_name":"/bootstrap","source":"stderr","log":"","tag":"docker.b6c4faf1c321"}
2020-01-15 22:45:34 +0000 [warn]: #0 dump an error event: error_class=Fluent::Plugin::Parser::ParserError error="pattern not match with data 'goroutine 19 [running]:'" location=nil tag="docker.b6c4faf1c321" time=1579128334 record={"log"=>"goroutine 19 [running]:", "container_id"=>"b6c4faf1c321c93330fc1bc6d667dbae35b1723a99e0ccdb722b9ee95a406900", "container_name"=>"/bootstrap", "source"=>"stderr"}
{"log":"goroutine 19 [running]:","container_id":"b6c4faf1c321c93330fc1bc6d667dbae35b1723a99e0ccdb722b9ee95a406900","container_name":"/bootstrap","source":"stderr","tag":"docker.b6c4faf1c321"}
2020-01-15 22:45:34 +0000 [warn]: #0 dump an error event: error_class=Fluent::Plugin::Parser::ParserError error="pattern not match with data 'main.main.func1(0x0)'" location=nil tag="docker.b6c4faf1c321" time=1579128334 record={"container_id"=>"b6c4faf1c321c93330fc1bc6d667dbae35b1723a99e0ccdb722b9ee95a406900", "container_name"=>"/bootstrap", "source"=>"stderr", "log"=>"main.main.func1(0x0)"}
{"container_id":"b6c4faf1c321c93330fc1bc6d667dbae35b1723a99e0ccdb722b9ee95a406900","container_name":"/bootstrap","source":"stderr","log":"main.main.func1(0x0)","tag":"docker.b6c4faf1c321"}
2020-01-15 22:45:34 +0000 [warn]: #0 dump an error event: error_class=Fluent::Plugin::Parser::ParserError error="pattern not match with data '\t/go/src/github.com/spacemeshos/go-spacemesh/cmd/integration/harness.go:95 +0x3a'" location=nil tag="docker.b6c4faf1c321" time=1579128334 record={"source"=>"stderr", "log"=>"\t/go/src/github.com/spacemeshos/go-spacemesh/cmd/integration/harness.go:95 +0x3a", "container_id"=>"b6c4faf1c321c93330fc1bc6d667dbae35b1723a99e0ccdb722b9ee95a406900", "container_name"=>"/bootstrap"}
{"source":"stderr","log":"\t/go/src/github.com/spacemeshos/go-spacemesh/cmd/integration/harness.go:95 +0x3a","container_id":"b6c4faf1c321c93330fc1bc6d667dbae35b1723a99e0ccdb722b9ee95a406900","container_name":"/bootstrap","tag":"docker.b6c4faf1c321"}
2020-01-15 22:45:34 +0000 [warn]: #0 dump an error event: error_class=Fluent::Plugin::Parser::ParserError error="pattern not match with data 'created by main.main'" location=nil tag="docker.b6c4faf1c321" time=1579128334 record={"container_name"=>"/bootstrap", "source"=>"stderr", "log"=>"created by main.main", "container_id"=>"b6c4faf1c321c93330fc1bc6d667dbae35b1723a99e0ccdb722b9ee95a406900"}
{"container_name":"/bootstrap","source":"stderr","log":"created by main.main","container_id":"b6c4faf1c321c93330fc1bc6d667dbae35b1723a99e0ccdb722b9ee95a406900","tag":"docker.b6c4faf1c321"}
2020-01-15 22:45:34 +0000 [warn]: #0 dump an error event: error_class=Fluent::Plugin::Parser::ParserError error="pattern not match with data '\t/go/src/github.com/spacemeshos/go-spacemesh/cmd/integration/harness.go:92 +0x390'" location=nil tag="docker.b6c4faf1c321" time=1579128334 record={"log"=>"\t/go/src/github.com/spacemeshos/go-spacemesh/cmd/integration/harness.go:92 +0x390", "container_id"=>"b6c4faf1c321c93330fc1bc6d667dbae35b1723a99e0ccdb722b9ee95a406900", "container_name"=>"/bootstrap", "source"=>"stderr"}
{"log":"\t/go/src/github.com/spacemeshos/go-spacemesh/cmd/integration/harness.go:92 +0x390","container_id":"b6c4faf1c321c93330fc1bc6d667dbae35b1723a99e0ccdb722b9ee95a406900","container_name":"/bootstrap","source":"stderr","tag":"docker.b6c4faf1c321"}
```

Here's what I see from testnet.py:

```
> python testnet.py
created
fluent running
Creating poet container
Creating bootstrap container
bootstrap params: --randcon 4 --hare-committee-size 5 --hare-max-adversaries 2 --hare-round-duration-sec 10 --layer-duration-sec 60 --layer-average-size 10 --hare-wakeup-delta 10 --test-mode  --grpc-server  --json-server  --eligibility-confidence-param 5 --eligibility-epoch-offset 0 --genesis-active-size 5 --genesis-conf /tmp/genesis.json --genesis-time 2020-01-15T22:46:31+00:00 --coinbase 097598942e44919cf7d11499887a595e41b097acd0a75d65ed8b8c6fa739d297 --poet-server 192.168.0.20:50002 --events-url tcp://0.0.0.0:56565
Waiting for node to boot up
(hangs)
^CRun stopped
Starting to shutdown nodes
Killing all dockers
[-cannot remove cont
-cannot remove cont
-
```

**Comment by avive** [comment]
@moshababo - is localnet working again?
@lrettig - is this better now with the new instructions on how to build & run go-sm and join tn 0.1?

**Comment by lrettig** [comment]
I don't know what caused the above issue, but by blowing away my local-testnet directory completely and redoing things from scratch on macOS, it's now working. It may have been a docker issue or something. There's nothing remaining to be done here.
